server:
  port: 8080
  compression:
    enabled:  true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript
spring:
  aop:
    auto: true
  thymeleaf:
    cache:  false
    mode: HTML5
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  oracle.jdbc.OracleDriver
  profiles:
    active: dev
  http:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
db:
  url:  jdbc:oracle:thin:@116.62.113.181:1627:alydb
  username: kpi
  password: Zpmckpi1234
mybatis:
  type-aliases-package: com.shmut.ocr.dal.entity
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout:  30
#
#endpoints:
#  beans:
#    sensitive:  false
#  shutdown:
#    enabled:  true
#management:
#  security:
#    enabled:  false
#  port: 11111

logging:
  level:
    ROOT: INFO

security:
  ignored:  '/**'
  basic:
    enable: false
