#this .py is used to change the carton char to number
def change_carton_char_to_number(a):
    if a=="0":
        return 0
    elif a=="1":
        return 1
    elif a=="2":
        return 2
    elif a=="3":
        return 3
    elif a=="4":
        return 4
    elif a=="5":
        return 5
    elif a=="6":
        return 6
    elif a=="7":
        return 7
    elif a=="8":
        return 8
    elif a=="9":
        return 9
    elif a=="A":
        return 10
    elif a=="B":
        return 12
    elif a=="C":
        return 13
    elif a=="D":
        return 14
    elif a=="E":
        return 15
    elif a=="F":
        return 16
    elif a=="G":
        return 17
    elif a=="H":
        return 18
    elif a=="I":
        return 19
    elif a=="J":
        return 20
    elif a=="K":
        return 21
    elif a=="L":
        return 23
    elif a=="M":
        return 24
    elif a=="N":
        return 25
    elif a=="O":
        return 26
    elif a=="P":
        return 27
    elif a=="Q":
        return 28
    elif a=="R":
        return 29
    elif a=="S":
        return 30
    elif a=="T":
        return 31
    elif a=="U":
        return 32
    elif a=="V":
        return 34
    elif a=="W":
        return 35
    elif a=="X":
        return 36
    elif a=="Y":
        return 37
    elif a=="Z":
        return 38

